<a href="https://colab.research.google.com/github/sindhuk14/Sindhuk14/blob/main/Copy_of_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [12]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [23]:
1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

SyntaxError: ignored

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [18]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)

array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=a + b
print(c)

[5 7 9]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [19]:
import pandas as pd
data = [10,20,30]
df = pd.DataFrame(data, columns=['Numbers'])
df

Numbers
0       10
1       20
2       30

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [24]:
a=pd.date_range(start='1/1/2023', end='10/2/2023')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
# import pandas as pd  

import pandas as pd   

      
# List1   

lst = [['Geek', 25], ['is', 30],  

       ['for', 26], ['Geeksforgeeks', 22]]  

  
# creating df object with columns specified     

df = pd.DataFrame(lst, columns =['Tag', 'number'])  

print(df )

             Tag  number
0           Geek      25
1             is      30
2            for      26
3  Geeksforgeeks      22
